# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GOOGLE_APPLICATION_CREDENTIALS: credentials.json
  GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
  GOOGLE_DRIVE_RSC_SKINS: ${{ secrets.GOOGLE_DRIVE_RSC_SKINS }}
  GOOGLE_DRIVE_RS_SKINS: ${{ secrets.GOOGLE_DRIVE_RS_SKINS }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install nsis
        run: sudo apt install -y nsis
      - name: Install pipenv
        run: python -m pip install pipenv
      - name: sync pipenv
        run: pipenv sync
      - name: credentials.json
        run: echo "$GOOGLE_CREDS" > credentials.json
      - name: Run the downloader
        run: pipenv run python rs-skin-downloader.py
      - name: Rename the zip to include the version
        run: mv "RS-Skins.zip" "RS-Skins-${{ env.GITHUB_REF_NAME }}.zip"
      - name: Package to Exe installer
        run: |
          cp rs-skins.nsi Staging/
          cd Staging
          makensis rs-skins.nsi
          mv "RS Skins.exe" "RS Skins ${{ env.GITHUB_REF_NAME }}.exe"
      - name: Release to Github Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            "Staging/RS Skins ${{ env.GITHUB_REF_NAME }}.exe"
            "RS-Skins-${{ env.GITHUB_REF_NAME }}.zip"
