# This is a basic workflow to help you get started with Actions

name: Package and Release

# Controls when the workflow will run
on:
  # push:
  #   tags: 
  #     - v*
  #     - beta*
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install nsis
        run: sudo apt install -y nsis
      - name: Install pipenv
        run: python -m pip install pipenv
      - name: sync pipenv
        run: pipenv sync
      - name: credentials.json
        run: echo "$GOOGLE_CREDS" > credentials.json
      - name: gdrive_secret.yml
        run: echo "$GOOGLE_DRIVE_FOLDERS" > gdrive_secret.yml
      - name: Run the downloader
        run: pipenv run python rs-liveries-downloader.py
      - name: Package to Exe installer
        run: |
          cd Staging
          makensis -V4 -DVERSION=$GITHUB_REF rs-liveries-rendered.nsi
          mv "RS Liveries.exe" "RS_Liveries_$GITHUB_REF_NAME.exe"
      - name: Release to Github Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Staging/RS_Liveries_${{ github.ref_name }}.exe
