---
name: Bake the installer (non-main release - on push)

on:

  push:
    branches:
      - 'feature**'
      - 'test**'
      - 'hotfix**'
      - 'bug**'
      - 'wip**'
      - 'dev**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      runner: self-hosted
    secrets:
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      ASSETS: ${{ secrets.ASSETS }}
