---
name: Bake the installer (main - on push)

on:

  push:
    branches:
      - 'main'
      - 'debug**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      upload_artifact_suffix: " - Main OnPush"
      runner: 'ubuntu-22.04'
      minimal_sample_size: true
      testing_release: false
      main_release: false
    secrets:
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      ASSETS: ${{ secrets.ASSETS }}
