---
name: Download, parse, compress and create the installer

on:

  push:
    branches:
      - 'feature/*'
      - 'test*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
  GOOGLE_DRIVE_FOLDERS: ${{ secrets.GOOGLE_DRIVE_FOLDERS }}

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      runner: self-hosted
