---
name: Bake the installer - On release

on:

  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dry_run:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      runner: ${{ startsWith( github.ref_name, 'test' ) && 'self-hosted' || 'ubuntu-22.04' }}
      upload_artifact_suffix: " - Dry run"
      minimal_sample_size: true
      testing_release: false
      main_release: false
    secrets:
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      ASSETS: ${{ secrets.ASSETS }}
  main_release:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      upload_artifact_suffix: " - Release"
      runner: ${{ startsWith( github.ref_name, 'test' ) && 'self-hosted' || 'ubuntu-22.04' }}
      minimal_sample_size: false
      testing_release: false
      main_release: true
    secrets:
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      ASSETS: ${{ secrets.ASSETS }}
  virustotal:
    needs: main_release
    runs-on: ${{ startsWith( github.ref_name, 'test' ) && 'self-hosted' || 'ubuntu-22.04' }}
    steps:
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            .exe$
