---
name: Download, parse, compress and create the installer

on:

    release:
      types: [published]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  
jobs:
    debug:
        runs-on: ubuntu-22.04
        steps:
            - name: test
              run: echo $GITHUB_REF
    call_reusable_workflow:
        uses: ./.github/workflows/reusable_workflow.yml
        with:
            runner: ${{ startsWith( github.ref, 'test' ) && 'self-hosted' || 'ubuntu-22.04' }}
