# This is a basic workflow to help you get started with Actions

name: Windows Package and Release

# Controls when the workflow will run
on:
  push:
    branches: 
      - beta
  # release:
  #   types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
  GOOGLE_DRIVE_FOLDERS: ${{ secrets.GOOGLE_DRIVE_FOLDERS }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package-and-release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     root-reserve-mb: 20480
      #     swap-size-mb: 1024
      #     remove-dotnet: 'true'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: choco install nsis wget unzip
      - run: |
          wget https://nsis.sourceforge.io/mediawiki/images/c/cf/NewAdvSplash.zip
          cd "C:\Program Files (x86)\NSIS"
          unzip D:\a\rs-skins\rs-skins\NewAdvSplash.zip
          cd D:\a\rs-skins\rs-skins
          python -m pip install pipenv
          del Pipenv.lock
          pipenv install
          echo %GOOGLE_CREDS% > credentials.json
          echo %GOOGLE_DRIVE_FOLDERS% > gdrive_secret.yml
          pipenv run python rs_liveries_downloader.py
