# This is a basic workflow to help you get started with Actions

name: Windows Package and Release

# Controls when the workflow will run
on:
  push:
    branches: 
      - beta
  # release:
  #   types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
  GOOGLE_DRIVE_FOLDERS: ${{ secrets.GOOGLE_DRIVE_FOLDERS }}
  WSLENV: GOOGLE_CREDS:GOOGLE_DRIVE_FOLDERS


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package-and-release:
    # The type of runner that the job will run on
    # runs-on: windows-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run Downloader in bash
        run: |
          # wsl --install -d Ubuntu-22.04 ## THIS IS A PREREQ
          wsl -u root -d Ubuntu-22.04 -- apt update
          wsl -u root -d Ubuntu-22.04 -- apt install python3.10
          wsl -u root -d Ubuntu-22.04 -- wget https://bootstrap.pypa.io/get-pip.py
          wsl -u root -d Ubuntu-22.04 -- python3.10 get-pip.py
          wsl -u root -d Ubuntu-22.04 -- python3.10 -m pip install pipenv
          $Env:GOOGLE_CREDS | Out-File -FilePath credentials.json
          $Env:GOOGLE_DRIVE_FOLDERS | Out-File -FilePath gdrive_secret.yml
          [System.IO.File]::WriteAllLines(credentials.json,   $Env:GOOGLE_CREDS)
          [System.IO.File]::WriteAllLines(gdrive_secret.json, $Env:GOOGLE_DRIVE_FOLDERS)
          bash -c "pipenv sync"
          bash -c "pipenv run python rs_liveries_downloader.py"
      - name: Prep Makensis
        run: |
          Invoke-WebRequest -Uri https://nsis.sourceforge.io/mediawiki/images/c/cf/NewAdvSplash.zip -OutFile NewAdvSplash.zip
          Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/NewAdvSplash.zip", "$PWD")
          Copy-Item  Contrib\NewAdvSplash             "C:\Program Files (x86)\NSIS\Contrib\"
          Copy-Item  Plugins\newadvsplash.dll         "C:\Program Files (x86)\NSIS\Plugins\x86-ansi\"
          Copy-Item  Unicode\plugins/newadvsplash.dll "C:\Program Files (x86)\NSIS\Plugins\x86-unicode\"
      - name: Makensis
        run: |
          cd Staging
          & "C:\Program Files (x86)\NSIS\makensis.exe" /V4 /DVERSION=%GITHUB_REF% rs-liveries-rendered.nsi
          Move-Item "RS Liveries.exe" "RS_Liveries_%GITHUB_REF_NAME%.exe"
      # - name: Release to Github Releases
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       Staging/RS_Liveries_${{ github.ref_name }}.exe
      #       Staging/rs-liveries-rendered.nsi
      #       Staging/rs-liveries-pilot-priorities.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: Liveries Installer
          path: Staging\RS_Liveries_{{ GITHUB_REF_NAME }}.exe
          retention-days: 1
